### ISSUE TITLE
Drop C compiler pin

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/kubo-feedstock#10]
Currently this is pinned to use GCC 10. Would be good to relax this so the latest GCC can be used.

https://github.com/conda-forge/kubo-feedstock/blob/81ad90eb5a09f1ff71f795f5875d456b7627fcbc/recipe/conda_build_config.yaml#L10-L11

**Comment by bollwyvl** [comment]
Looks like this worked on https://github.com/conda-forge/kubo-feedstock/pull/17
