### ISSUE TITLE
osx-arm64 support?

### ISSUE THREAD

**Issue by hadim** [conda-forge/kubo-feedstock#20]
### Comment:

I am not familiar with Go-based packages. Any idea whether it will be hard to support an osx-arm64 package for kubo?

ping @conda-forge/kubo

**Comment by bollwyvl** [comment]
Can try... https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4858

**Comment by bollwyvl** [comment]
That was merged: will wait to see what the bot thinks.

**Comment by hadim** [comment]
Thanks @bollwyvl!

**Comment by bollwyvl** [comment]
Closed by #21. Please open a new issue if it's busted.

**Comment by hadim** [comment]
I confirm it works on an M2 laptop. Almost too easy!

Thanks again!
