### ISSUE TITLE
kubo 0.17 windows not uploading

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/kubo-feedstock#5]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=616857&view=logs&j=8af117b0-dfa5-5d1c-b02e-a448dd16efdb&t=4265c329-aa86-5dee-9c6a-586eb4d214ce&l=10
```
[ERROR] Trouble reading metadata from D:\bld\win-64\kubo-0.17.0-h07f9b4e_0.conda. Is this a valid conda package?
[ERROR] Trouble reading metadata from D:\bld\win-64\kubo-0.17.0-h07f9b4e_0.conda. Is this a valid conda package?
Failed to upload due to Command '['anaconda', '--quiet', '-t', 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpdifa5eov\\binstar.token', 'upload', 'D:\\bld\\win-64\\kubo-0.17.0-h07f9b4e_0.conda', '--user=cf-staging', '--channel=main']' returned non-zero exit status 1.. Trying again in 153.93679428100586 seconds
Traceback (most recent call last):
  File "C:\Miniforge\Scripts\upload_package-script.py", line 10, in <module>
    sys.exit(upload_package())
  File "C:\Miniforge\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Miniforge\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Miniforge\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Miniforge\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Miniforge\lib\site-packages\conda_forge_ci_setup\build_utils.py", line 235, in upload_package
    retry_upload_or_check(
  File "C:\Miniforge\lib\site-packages\conda_forge_ci_setup\upload_or_check_non_existence.py", line 315, in retry_upload_or_check
    raise TimeoutError("Did not manage to upload package.  Failing.")
TimeoutError: Did not manage to upload package.  Failing.

```

### Installed packages

```shell
kubo
```

### Environment info

```shell
windows
```

**Comment by jakirkham** [comment]
Maybe try following [this doc to upload debug packages on Azure]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#downloading-prebuilt-packages-from-ci ). This can be done in a PR. Then can try inspecting those binaries to figure out what went wrong.

**Comment by bollwyvl** [comment]
Hm, looking at: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=617179&view=artifacts&pathAsName=false&type=publishedArtifacts

- `conda-verify` doesn't know what to do with `.conda`
- flip-flopping through `cph`, it just complains about license
  ```
  kubo-0.17.0-h07f9b4e_0.tar.bz2: C1115 Found invalid license "Apache-2.0 or MIT" in info/index.json
  ```
- the `cph verify` fails with
```
 Traceback (most recent call last):
  File "/home/weg/mf/bin/cph", line 11, in <module>
    sys.exit(main())
  File "/home/weg/mf/lib/python3.10/site-packages/conda_package_handling/cli.py", line 159, in main
    failed_files = api.verify_conversion(
  File "/home/weg/mf/lib/python3.10/site-packages/conda_package_handling/api.py", line 161, in verify_conversion
    with _Executor(max_workers=processes) as executor:
NameError: name '_Executor' is not defined. Did you mean: 'executor'?
```

**Comment by mbargull** [comment]
> `NameError: name '_Executor' is not defined. Did you mean: 'executor'?`

Could you report this as a bug at https://github.com/conda/conda-package-handling/issues ?

----
But the above is likely not the problem here (`verify_conversion` isn't run in the CI AIUI).
It's probably as mundane as a permission issue while writing a temporary file. The log shows:
```
C:\Users\VSSADM~1\AppData\Local\Temp\conda-6018\conda.tmp - Access is denied.
```
which, after inspecting `anaconda-client`'s source, makes sense since the `Trouble reading metadata` error comes from a place that swallows the traceback by default. We might want to run `anaconda-client` with the `---show-traceback` option to not swallow it.

(As for why this happens for this feedstock and why it happened in the second CI run attempt, too -- I have no idea.)

**Comment by jakirkham** [comment]
Raised issue ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/215 ) about having some way to enable debug uploads

**Comment by bollwyvl** [comment]
> report this as a bug

Created: https://github.com/conda/conda-package-handling/issues/164

> happens for this feedstock

yeah, dunno: maybe some part of the `go` build (or test procedure) doesn't clean up very well after itself, which bothers `conda` later...

**Comment by bollwyvl** [comment]
Maybe overloading `%TEMP%` or `%TMP%` or whatever it is on windows would work...

**Comment by jakirkham** [comment]
Per ( https://github.com/conda/conda-package-handling/issues/164 ), it looks like upgrading `conda-package-handling` ( https://github.com/conda-forge/conda-package-handling-feedstock/pull/69 ) will fix this. Though that is being postponed until after the holidays

**Comment by jakirkham** [comment]
Interesting could we override the temporary directory used by Go during the build?

**Comment by mbargull** [comment]
> yeah, dunno: maybe some part of the `go` build (or test procedure) doesn't clean up very well after itself, which bothers `conda` later...

Oh, I didn't even look at the package/recipe. Yeah, if this is a Go one, then most probably.
IDK why Go builds change permissions in the temp dir. Other permission issues concerning the module cache are taken care of in this recipe via `-modcacherw`. But for the `%TEMP%` one I don't know of a conventional solution..


> Interesting could we override the temporary directory used by Go during the build?

Something like
```sh
export GOTMPDIR="$(pwd)/tmp"
mkdir -p "${GOTMPDIR}"
... build ...
rm -rf "${GOTMPDIR}"
```
could be tried.

**Comment by bollwyvl** [comment]
Tried the `GOTMPDIR` (thanks!)... still [seeing this at the beginning of `test`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=617359&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=1334) 

```
C:\Users\VSSADM~1\AppData\Local\Temp\conda-29801\conda.tmp - Access is denied.
```

so presumably wouldn't continue. Will wait for CPH 2000 to investigate further...

**Comment by jakirkham** [comment]
Recently `conda-package-handling` version `2.0.1` was added to `conda-forge` ( https://github.com/conda-forge/conda-package-handling-feedstock/pull/68 ), which fixes issue ( https://github.com/conda/conda-package-handling/issues/164 ).

That said, it looks like this is [still failing on Windows]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=621012&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802 ). This appears to be due to issue ( https://github.com/conda/conda-package-handling/issues/167 ). Namely running out of memory during Zstd compression.

To fix this, we need PR ( https://github.com/conda/conda-build/pull/4650 ) to set the compression level lower than the default value (`22`). This is being included in a hot-fix of `conda-build` version [3.23.2]( https://github.com/conda/conda-build/releases/tag/3.23.2 ), which should be out shortly ( https://github.com/conda-forge/conda-build-feedstock/pull/190 ).

**Comment by bollwyvl** [comment]
Thanks for the update! I'll take a look tomorrow, unless someone comes demanding `win-64/kubo-0.17.conda` with a knife in the next 24hrs!

**Comment by mbargull** [comment]
:hocho: :grimacing:

One of us can just try to restart the CI build in an hour or so when the new conda-build release is up and running.

**Comment by jakirkham** [comment]
Yep that was my plan 👍

**Comment by jakirkham** [comment]
Retrying [CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=621012&view=logs&j=8af117b0-dfa5-5d1c-b02e-a448dd16efdb&t=e2c75a56-c034-56aa-1054-1177210cf8d6 ). It's possible something is still missing, but hopefully this will shed a light on what still remains.

**Comment by jakirkham** [comment]
Looks like [the upload still fails]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=621012&view=logs&j=8af117b0-dfa5-5d1c-b02e-a448dd16efdb&t=2ea31798-5e21-58b8-11d2-4183ea461dbf ) due to the original error

**Comment by jakirkham** [comment]
Tried another build earlier and it still fails

**Comment by jakirkham** [comment]
FWIW grabbed the package from the artifacts generated by the last build and downloaded it. Was able to upload [the package produced to my own channel]( https://anaconda.org/jakirkham/kubo/files ).

Am not sure why CI in particular struggles with this, but think we will need to gather more info from CI.

**Comment by jakirkham** [comment]
We've added [a flag to show the traceback when uploads fail]( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/ec0684d64b454fc7cdaf65c76b8b3a26f7f5d9e0/recipe/conda_forge_ci_setup/upload_or_check_non_existence.py#L104 ). Have restarted [the CI build]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=621012&view=logs&j=6759efb3-429c-5693-5603-83bb6d6f3628 ). Let's see what that shows us

**Comment by bollwyvl** [comment]
First-class service!

**Comment by jakirkham** [comment]
So looking at [the recent CI build]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=621012&view=logs&j=6759efb3-429c-5693-5603-83bb6d6f3628&t=f91995bb-7e23-54f1-e44e-6d6e575f04a3 ), (also [attached log]( https://github.com/conda-forge/kubo-feedstock/files/10137275/kubo-feedstock_20221130.2_win_64.txt ) for posterity) am seeing the following traceback. It looks like there are some leftover file handles that block the upload from proceeding.

<details>
<summary>Traceback from upload:</summary>

```python
[ERROR] Trouble reading metadata from D:\bld\win-64\kubo-0.17.0-h07f9b4e_0.conda. Is this a valid conda package?
[ERROR] 
Traceback (most recent call last):
  File "C:\Miniforge\Scripts\anaconda-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Miniforge\lib\site-packages\binstar_client\scripts\cli.py", line 158, in main
    binstar_main(command_module, args, exit,
  File "C:\Miniforge\lib\site-packages\binstar_client\scripts\cli.py", line 138, in binstar_main
    return args.main(args)
  File "C:\Miniforge\lib\site-packages\binstar_client\commands\upload.py", line 315, in main
    package_info = upload_package(
  File "C:\Miniforge\lib\site-packages\binstar_client\commands\upload.py", line 189, in upload_package
    package_attrs, release_attrs, file_attrs = get_attrs(package_type, filename, parser_args=args)
  File "C:\Miniforge\lib\site-packages\binstar_client\utils\detect.py", line 144, in get_attrs
    return inspector(filename, fileobj, *args, **kwargs)
  File "C:\Miniforge\lib\site-packages\binstar_client\inspect_package\conda.py", line 157, in inspect_conda_package
    rmtree(tmpdir)
  File "C:\Miniforge\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Miniforge\lib\shutil.py", line 624, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Miniforge\lib\shutil.py", line 629, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Miniforge\lib\shutil.py", line 627, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpj_6_8z82\\info\\about.json'
Failed to upload due to Command '['anaconda', '--quiet', '--show-traceback', '-t', 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpzqi9l_83\\binstar.token', 'upload', 'D:\\bld\\win-64\\kubo-0.17.0-h07f9b4e_0.conda', '--user=cf-staging', '--channel=main']' returned non-zero exit status 1.. Trying again in 10 seconds
```

</details>

In fact looking earlier in the build, similar issues are spotted by `conda-build` during cleanup (think Marcel saw something similar above). It is also worth noting that the Go temporary directory set appears to go unused. So maybe we need to do something else for that to take affect.

<details>
<summary>Removal warning during build:</summary>

```python
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(143): Could not remove or rename C:\Users\VSSADM~1\AppData\Local\Temp\tmpnzjj3ftb\bin\ipfs.exe.  Please remove this file manually (you may need to reboot to free file handles)
```

</details>

Not entirely sure what is causing the issue, but it does seem to be some issue cleaning up used resources.

cc @nehaljwani (in case you have more insight into the Go & Windows build issues encountered here)

**Comment by mbargull** [comment]
I didn't figure out the root cause regarding the temp file access/`anaconda upload` problems on Windows.
Meaning, I still don't know what causes access right changes to the temp folder during `conda-build` runs.
But at least I now know why we see the upload problems lately:
For the `.conda` rollout we updated to `anaconda-client>=1.11` since it handles `.conda`.
The previously used `anaconda-client=1.8` didn't use a temp folder, hence we didn't have the issue then.
Now, `binstar_client.inspect_package.conda.inspect_conda_package` extracts the package's `info` component to a temporary directory.
Since something during our build changes permissions in `%TEMP%`, uploading `.conda.` fails on Windows.

**Comment by jakirkham** [comment]
Hmm...interesting. Thanks Marcel 🙏

Is there a way to tell `anaconda-client` to use a different temporary directory? Or should we stick to trying to get Go to use a different package directory?

**Comment by jakirkham** [comment]
Re-rendering in PR ( https://github.com/conda-forge/kubo-feedstock/pull/8 ) with the change Marcel linked above. This fixed a similar issue seen when releasing `conda`. Hopefully this also addresses the issue seen here

**Comment by bollwyvl** [comment]
Reopened this, watching the build here: https://github.com/conda-forge/kubo-feedstock/runs/9914111996

**Comment by bollwyvl** [comment]
Looks good! Thanks all!

**Comment by jakirkham** [comment]
Great glad it worked! 😀
